import type { PluginServerContext } from "@getpaseo/plugin/server";
import { hostHealthRpc } from "./shared/health-contracts.ts";
import { hostSavingsRpc } from "./shared/savings-contracts.ts";
import { readHostSavings } from "./server/host-savings.ts";
import { readHostHealth } from "./server/host-health.ts";
import { NativeFolderPicker } from "./server/native-picker.ts";
import { nativePickerCapabilitiesRpc, nativePickerStartRpc, nativePickerPollRpc, nativePickerCancelRpc } from "./shared/native-picker-contracts.ts";
import { catalogRpc, directoryRpc, inspectRpc, preferences, searchRpc, statusRpc, symbolRpc } from "./shared/contracts.ts";
import { DirectoryBrowser } from "./server/directory-browser.ts";
import { GortexClient } from "./server/gortex-client.ts";
import { WorkspaceLibrary } from "./server/workspace-library.ts";
import { RepositoryMetadata } from "./server/repository-metadata.ts";
import { RepositoryAdminLock } from "./server/repository-admin-lock.ts";
import { RepositoryUntrack } from "./server/repository-untrack.ts";
import { RepositoryTrack } from "./server/repository-track.ts";
import { GortexUpdates } from "./server/gortex-updates.ts";
import { updateStatusRpc, updateCheckRpc, updatePreviewRpc, updateApplyRpc, updateJobRpc } from "./shared/update-contracts.ts";
import { trackPreviewRpc, trackApplyRpc, trackJobRpc } from "./shared/track-contracts.ts";
import { untrackPreviewRpc, untrackApplyRpc, untrackJobRpc } from "./shared/untrack-contracts.ts";
import { metadataReadRpc, metadataPreviewRpc, metadataRepairRpc, metadataApplyRpc, metadataJobRpc } from "./shared/metadata-contracts.ts";

import { RepositoryWorktrees } from "./server/repository-worktrees.ts";
import { worktreesRpc } from "./shared/worktree-contracts.ts";

import { hostTimeRpc } from "./shared/date-time.ts";
import { AutoIndexer } from "./server/auto-index.ts";
import { autoIndexActivityRpc } from "./shared/auto-index-contracts.ts";
import { GitInitializer } from "./server/git-init.ts";
import { gitInitRpc, gitStatusRpc } from "./shared/git-contracts.ts";
import { ExclusionSuggester } from "./server/exclusion-suggester.ts";
import { suggestJobRpc, suggestLatestRpc, suggestStartRpc } from "./shared/exclusion-suggest-contracts.ts";
import { PluginUpdater } from "./server/plugin-updater.ts";
import { pluginUpdateApplyRpc, pluginUpdateCheckRpc } from "./shared/plugin-update-contracts.ts";

export default function contribute(server: PluginServerContext) {
  server.handle(hostTimeRpc, () => {
    const { timeZone, locale } = new Intl.DateTimeFormat().resolvedOptions();
    return { timeZone, locale };
  });
  const nativePicker = new NativeFolderPicker();
  server.handle(hostHealthRpc, () => readHostHealth(native));
  server.handle(hostSavingsRpc, readHostSavings);
  server.handle(nativePickerCapabilitiesRpc, () => nativePicker.capabilities());
  server.handle(nativePickerStartRpc, ({ initialPath }) => nativePicker.start(initialPath));
  server.handle(nativePickerPollRpc, ({ id }) => nativePicker.poll(id));
  server.handle(nativePickerCancelRpc, ({ id }) => nativePicker.cancel(id));
  const native = new GortexClient();
  const library = new WorkspaceLibrary(native);
  const worktrees = new RepositoryWorktrees(native);
  server.handle(worktreesRpc, ({ path, offset }) => worktrees.list(path, offset));
  const directories = new DirectoryBrowser();
  const settings = server.registerSettings(preferences);
  server.handle(catalogRpc, input => library.catalog(input.offset, input));
  server.handle(directoryRpc, input => directories.list(input));
  server.handle(inspectRpc, input => library.inspect(input.path));
  server.handle(statusRpc, input => library.status(input));
  server.handle(searchRpc, input => library.search(input));
  server.handle(symbolRpc, input => library.symbol(input));
  const admin = new RepositoryAdminLock();
  const metadata = new RepositoryMetadata(native, undefined, () => library.close(), admin);
  const untrack = new RepositoryUntrack(native, undefined, () => library.close(), admin);
  const track = new RepositoryTrack(native, () => library.close(), admin);
  const autoIndex = new AutoIndexer(track, metadata, async () => { const state = await settings.read(); return state.status === "ready" ? state.values : null; });
  // Background work: lifecycle hooks have a 30-second budget, and a skipped or failed run is recorded, not thrown.
  server.on("workspace.created", ({ workspace }) => { void autoIndex.handle(workspace); });
  const git = new GitInitializer(() => library.close());
  server.handle(gitStatusRpc, ({ path }) => git.status(path));
  server.handle(gitInitRpc, ({ path }) => git.initialize(path));
  const suggester = new ExclusionSuggester(metadata, async () => { const state = await settings.read(); return state.status === "ready" ? state.values.suggestionAgent : "claude/claude-sonnet-5"; });
  server.handle(suggestStartRpc, ({ path }, { paseo }) => suggester.start(path, paseo));
  server.handle(suggestJobRpc, ({ id }) => suggester.job(id));
  server.handle(suggestLatestRpc, async ({ path }) => ({ job: await suggester.latestFor(path) }));
  const pluginUpdater = new PluginUpdater();
  server.handle(pluginUpdateCheckRpc, () => pluginUpdater.check());
  server.handle(pluginUpdateApplyRpc, ({ target }) => pluginUpdater.apply(target));
  server.handle(autoIndexActivityRpc, () => ({ records: autoIndex.activity() }));
  const updates = new GortexUpdates(undefined, () => library.close(), admin, effect => native.withMaintenance(effect));
  server.handle(updateStatusRpc, () => updates.status());
  server.handle(updateCheckRpc, () => updates.check());
  server.handle(updatePreviewRpc, () => updates.preview());
  server.handle(updateApplyRpc, ({ id }) => updates.apply(id));
  server.handle(updateJobRpc, ({ id }) => updates.job(id));
  server.handle(trackPreviewRpc, ({ path }) => track.preview(path));
  server.handle(trackApplyRpc, ({ id }) => track.apply(id));
  server.handle(trackJobRpc, ({ id, observe }) => observe ? track.observe(id) : track.job(id));
  server.handle(untrackPreviewRpc, ({ path }) => untrack.preview(path));
  server.handle(untrackApplyRpc, ({ id }) => untrack.apply(id));
  server.handle(untrackJobRpc, ({ id }) => untrack.job(id));
  server.handle(metadataReadRpc, ({ path }) => metadata.read(path));
  server.handle(metadataPreviewRpc, ({ path, revision, configured, exclude }) => metadata.preview(path, revision, configured, exclude));
  server.handle(metadataRepairRpc, ({ path, revision }) => metadata.previewRepair(path, revision));
  server.handle(metadataApplyRpc, ({ id }) => metadata.apply(id));
  server.handle(metadataJobRpc, ({ id }) => metadata.job(id));
  return async () => { directories.close(); nativePicker.close(); await Promise.all([suggester.close(), autoIndex.close(), metadata.close(), untrack.close(), track.close(), updates.close(), worktrees.close()]); library.close(); await native.close(); };
}
